jwt:
  secret: "secret"

server:
  port: 8081
  # error:
  #   whitelabel:
  #     enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # mvc:
  #   throw-exception-if-no-handler-found: true
  # resources:
  #   add-mappings: false
